CREATE SCHEMA MEDANO;
USE MEDANO;

-- CREAR TABLA CLIENTES

CREATE TABLE IF NOT EXISTS CLIENTES(
ID_CL INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
NOMBRE_CL VARCHAR(30) NOT NULL,
APELLIDO_CL VARCHAR(30) NOT NULL,
CORREO_CL VARCHAR(50) DEFAULT 'NULL',
TEL_CL VARCHAR(20) NOT NULL UNIQUE,
FECHA_NAC_CL DATE
)ENGINE=InnoDB DEFAULT CHARSET utf8mb4;


-- CREAR TABLA CONSULTA HOMEOPATICA

CREATE TABLE IF NOT EXISTS CONSULTA_H(
NRO_ID_CH INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
NOMBRE_PROF_CH VARCHAR(30) NOT NULL,
APELLIDO_PROF_CH VARCHAR(30) NOT NULL,
ID_CL INT UNSIGNED NOT NULL,
FECHA_RES_CH DATE NOT NULL,
HORA_RES_CH TIME NOT NULL,
CONSTRAINT FKD_ID_CL_CH FOREIGN KEY(ID_CL) REFERENCES CLIENTES(ID_CL)
)ENGINE=InnoDB default CHARSET utf8mb4;

-- CREAR TABLA PRODUCTOS

CREATE TABLE IF NOT EXISTS PRODUCTOS(
ID_PRODUCTOS INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
MARCA VARCHAR(20) NOT NULL,
NOMBRE_PRODUCTO VARCHAR(20) NOT NULL,
STOCK INT,
CATEGORIA VARCHAR(20) NOT NULL
)ENGINE=INNODB DEFAULT CHARSET UTF8MB4;

-- CREAR TABLA PEDIDOS

CREATE TABLE IF NOT EXISTS PEDIDOS(
ID_PEDIDOS INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
ID_CL INT UNSIGNED NOT NULL,
ID_PRODUCTOS INT UNSIGNED NOT NULL,
FECHA_PEDIDOS DATE NOT NULL,
CONSTRAINT FKD_ID_CL_PEDIDOS FOREIGN KEY(ID_CL) REFERENCES CLIENTES(ID_CL),
CONSTRAINT FKD_ID_PRODUCTOS_PEDIDOS FOREIGN KEY(ID_PRODUCTOS) REFERENCES PRODUCTOS(ID_PRODUCTOS)
)ENGINE=INNODB DEFAULT CHARSET UTF8MB4;


-- CREAR TABLA PROVEEDORES

CREATE TABLE IF NOT EXISTS PROVEEDORES(
ID_PROVEEDORES INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
ID_PRODUCTOS INT UNSIGNED NOT NULL,
NOMBRE_PROVEEDORES VARCHAR(30) NOT NULL,
DIRECCION_PROVEEDORES VARCHAR(30) NOT NULL,
TEL_PROVEEDORES VARCHAR (20) NOT NULL UNIQUE,
CONSTRAINT FKD_ID_PRODUCTOS_PROVEEDORES FOREIGN KEY (ID_PRODUCTOS) REFERENCES PRODUCTOS(ID_PRODUCTOS)
)ENGINE=InnoDB DEFAULT CHARSET utf8mb4;

-- CREAR TABLA EMPLEADOS

CREATE TABLE IF NOT EXISTS EMPLEADOS(
ID_EMPLEADO INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
NOMBRE_EMPLEADO VARCHAR(30) NOT NULL,
APELLIDO_EMPLEADO VARCHAR(30) NOT NULL,
DIRECCION_EMPLEADO VARCHAR(30) NOT NULL,
TEL_EMPLEADO VARCHAR(30) NOT NULL UNIQUE,
CORREO_EMPLEADO VARCHAR(50) DEFAULT 'NULL'
)ENGINE=InnoDB DEFAULT CHARSET utf8mb4;

DROP TABLE EMPLEADOS;

-- CREAR TABLA VENTAS

CREATE TABLE IF NOT EXISTS VENTAS(
ID_VENTA INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
ID_EMPLEADO INT UNSIGNED NOT NULL,
ID_PEDIDOS INT UNSIGNED NOT NULL,
TOTAL VARCHAR(20) NOT NULL,
MODALIDAD_PAGO VARCHAR(20) NOT NULL,
CONSTRAINT FKD_ID_EMPLEADO_VENTAS FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
CONSTRAINT FKD_ID_PEDIDOS_VENTAS FOREIGN KEY(ID_PEDIDOS) REFERENCES PEDIDOS(ID_PEDIDOS)
)ENGINE=INNODB DEFAULT CHARSET UTF8MB4;


-- DROP SCHEMA MEDANO;


